version: "3"

services:
  web-service:
    build: .
    volumes:
      - "$PWD/..:/data/app"
    working_dir: "/data/app"
    networks:
      - default
    environment:
      APP_ENV: "dev"
      APP_INSTALL_DEPENDENCIES: "yes"
      COMPOSER_HOME: /data/app
      COMPOSE_HTTP_TIMEOUT: 9999
      DATABASE_DSN: pgsql://ecotone:secret@database:5432/ecotone
    ports:
      - 3000:80
  projections:
    build: .
    volumes:
      - "$PWD/..:/data/app"
    working_dir: "/data/app"
    user: 1000:1000
    networks:
      - default
    restart: always
    environment:
      APP_ENV: "dev"
      COMPOSER_HOME: /data/app
      COMPOSE_HTTP_TIMEOUT: 9999
      DATABASE_DSN: pgsql://ecotone:secret@database:5432/ecotone
    command: "/data/app/bin/console ecotone:run asynchronous_projections -vvv"
  database:
    image: postgres:12.1
    networks:
      - default
    environment:
      POSTGRES_USER: "ecotone"
      POSTGRES_PASSWORD: "secret"